export default `

- Javascript​:
  - ES6
  - Node
  - Flow
  - React
  - Express
  - MobX
  - RxJS
  - Redux
  - Packaging etc.
    - Babel
    - yarn
    - npm
    - lerna
    - Webpack
    - rollup
  - TDD/BDD
    - Jest
    - mocha
    - chai
    - webdriver
    - selenium
    - phantomJs
- Apps​:
  - Duh...
    - HTML5
    - CSS3
  - Web application & architecture security
    - Micro-services
    - OAuth1 and 2
  - REST API design
  - Websockets
    - Realtime API design
  - Accessibility
  - Mobile first/responsive
  - UI
    - Component-based design
    - Usability
    - A/B Testing
    - Micro-UIs
    - Mobile first/responsive
  - Backend
    - CRUD apps & APIs
    - Realtime data
    - API security
    - Heterogenous data
    - Architecture
      - Microservices
      - MQ
    - SOA
- Ops​:
  - Ansible
  - Docker
  - Consul
  - ZeroTier
  - AWS
  - haproxy
  - Apache
  - lighttpd
- Databases​:
  - SQL
    - PostgreSQL
    - MySQL
    - SQLite
    - Oracle
    - monetdb
  - NoSQL
    - MongoDB
    - Redis
    - InfluxDB
  - Schema design
  - Migrations
  - ORMs
  - ODMs
  - Optimisation
- General/Other​:
  - git
  - svn
  - TDD
  - Agile
    - Scrum
    - Kanban
    - SAFe
  - Information architecture
  - Hardware
  - General Linux admin.
`;
